name: Laravel CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test_db
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        volumes:
          - /home/runner/work/_temp/_github_home/mysql:/var/lib/mysql

    steps:
    - uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.1
        extensions: mbstring, pdo, mysql
        ini-values: post_max_size=256M, upload_max_filesize=256M
        coverage: none

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Copy .env.example to .env
      run: cp .env.example .env

    - name: Generate Laravel key
      run: php artisan key:generate

    - name: Migrate the database
      run: php artisan migrate

    - name: Run Laravel tests
      run: php artisan test
